-- MySQL Script generated by MySQL Workbench
-- Sun May 13 16:28:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `inicio` VARCHAR(5) NOT NULL,
  `fin` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Restaurante` (
  `idRestaurante` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `direccion` LONGTEXT NOT NULL,
  `clasificacion` INT(11) NOT NULL,
  `url` VARCHAR(250) NOT NULL,
  `calificacion` INT NULL,
  PRIMARY KEY (`idRestaurante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Horario_Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Horario_Restaurante` (
  `idHorario` INT NOT NULL,
  `idRestaurante` INT(11) NOT NULL,
  PRIMARY KEY (`idHorario`, `idRestaurante`),
  INDEX `fk_Horario_has_Restaurante_Restaurante1_idx` (`idRestaurante` ASC),
  INDEX `fk_Horario_has_Restaurante_Horario_idx` (`idHorario` ASC),
  CONSTRAINT `fk_Horario_has_Restaurante_Horario`
    FOREIGN KEY (`idHorario`)
    REFERENCES `restaurante`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_has_Restaurante_Restaurante1`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `restaurante`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Cupon` (
  `idCupon` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  PRIMARY KEY (`idCupon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Subcriptor_Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Subcriptor_Restaurante` (
  `idDueño` INT(11) NOT NULL AUTO_INCREMENT,
  `idRestaurante` INT(11) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `domicilio` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  PRIMARY KEY (`idDueño`),
  INDEX `fk_Dueño_Restaurante1_idx` (`idRestaurante` ASC),
  CONSTRAINT `fk_Dueño_Restaurante1`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `restaurante`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pago` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `caducidad` DATE NOT NULL,
  `codigo_seguridad` INT(11) NOT NULL,
  `numero_tarjeta` INT(11) NOT NULL,
  `titular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Platillo` (
  `idPlatillo` INT(11) NOT NULL AUTO_INCREMENT,
  `idRestaurante` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `precio` INT(11) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlatillo`),
  INDEX `fk_resta_idx` (`idRestaurante` ASC),
  CONSTRAINT `fk_resta`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `restaurante`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Promocion` (
  `idPromocion` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(80) NOT NULL,
  `idRestaurante` INT(11) NOT NULL,
  PRIMARY KEY (`idPromocion`),
  INDEX `fk_Promocion_Restaurante1_idx` (`idRestaurante` ASC),
  CONSTRAINT `fk_Promocion_Restaurante1`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `restaurante`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Reservacion` (
  `idReservacion` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `num_personas` INT(11) NOT NULL,
  `vigencia` VARCHAR(45) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `idRestaurante` INT(11) NOT NULL,
  `id_cupon` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idReservacion`),
  INDEX `fk_cliente_idx` (`idCliente` ASC),
  INDEX `resta_idx` (`idRestaurante` ASC),
  INDEX `fk_cupon_idx` (`id_cupon` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `restaurante`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cupon`
    FOREIGN KEY (`id_cupon`)
    REFERENCES `restaurante`.`Cupon` (`idCupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `resta`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `restaurante`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Telefono` (
  `idRestaurante` INT(11) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  INDEX `fkres_idx` (`idRestaurante` ASC),
  CONSTRAINT `fkres`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `restaurante`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(60) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurante`.`Pagos_Subscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pagos_Subscripcion` (
  `idSubscriptor` INT(11) NOT NULL,
  `idPago` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` DECIMAL NOT NULL,
  PRIMARY KEY (`idSubscriptor`, `idPago`),
  INDEX `fk_dueño_has_Pago_Pago1_idx` (`idPago` ASC),
  INDEX `fk_dueño_has_Pago_dueño1_idx` (`idSubscriptor` ASC),
  CONSTRAINT `fk_dueño_has_Pago_dueño1`
    FOREIGN KEY (`idSubscriptor`)
    REFERENCES `restaurante`.`Subcriptor_Restaurante` (`idDueño`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dueño_has_Pago_Pago1`
    FOREIGN KEY (`idPago`)
    REFERENCES `restaurante`.`Pago` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
